# Практична робота №1
## Робоче середовище і NumPy

**Виконав:** Коць Артем  
**Група:** ІТ-42  
**Варіант:** 9  
**Місто:** Суми

In [1]:
import numpy as np

print(np.__version__)

2.1.3


In [2]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


In [3]:
# Завдання 1

temps = np.array([-6, -5, 0, 9, 15, 18, 20, 19, 13, 7, 1, -4])

days_in_month = np.array([
    31, 28, 31, 30, 31, 30,
    31, 31, 30, 31, 30, 31
])

month_numbers = np.arange(1, 13)

print("Температури:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("\nКількість днів:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("\nНомери місяців:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

Температури: [-6 -5  0  9 15 18 20 19 13  7  1 -4]
shape: (12,)
dtype: int64

Кількість днів: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

Номери місяців: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [4]:
# Завдання 2

# Переведення температури з Цельсія у Фаренгейт
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

# Дні, коли температура вище 15°C
warm_days = days_in_month[temps > 15]

print("\nКількість днів у місяцях, де температура > 15°C:")
print(warm_days)

print("Всього теплих днів:", warm_days.sum())

# Перевірка кількості днів у році
print("\nСума днів у році:", days_in_month.sum())
print("365 днів:", days_in_month.sum() == 365)

Температура у °F:
[21.2 23.  32.  48.2 59.  64.4 68.  66.2 55.4 44.6 33.8 24.8]

Кількість днів у місяцях, де температура > 15°C:
[30 31 31]
Всього теплих днів: 92

Сума днів у році: 365
365 днів: True


In [5]:
# Завдання 3

# Найвища температура
max_index = temps.argmax()

print("Найвища температура:", temps[max_index], "°C")
print("Індекс найтеплішого місяця:", max_index)
print("Номер місяця:", month_numbers[max_index])

# Найнижча температура
min_index = temps.argmin()

print("\nНайнижча температура:", temps[min_index], "°C")
print("Індекс найхолоднішого місяця:", min_index)
print("Номер місяця:", month_numbers[min_index])

# Місяці з температурою нижче 0°C
below_zero = month_numbers[temps < 0]

print("\nМісяці з температурою нижче 0°C:")
print(below_zero)

# Сортування температур
sorted_temps = np.sort(temps)

print("\nТемператури за зростанням:")
print(sorted_temps)

print("\nПочатковий масив temps:")
print(temps)

Найвища температура: 20 °C
Індекс найтеплішого місяця: 6
Номер місяця: 7

Найнижча температура: -6 °C
Індекс найхолоднішого місяця: 0
Номер місяця: 1

Місяці з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-6 -5 -4  0  1  7  9 13 15 18 19 20]

Початковий масив temps:
[-6 -5  0  9 15 18 20 19 13  7  1 -4]


In [6]:
# Завдання 4

sun_hours = np.array([
    45, 60, 90, 140, 190, 220,
    240, 220, 160, 110, 60, 40
])

data = np.array([
    temps,
    days_in_month,
    sun_hours
])

print("Двовимірний масив:")
print(data)

print("\nФорма масиву:", data.shape)

print("\nСума по кожному рядку:")
print(data.sum(axis=1))

print("\nСереднє по кожному рядку:")
print(data.mean(axis=1))

print("\nСума по кожному стовпцю:")
print(data.sum(axis=0))

Двовимірний масив:
[[ -6  -5   0   9  15  18  20  19  13   7   1  -4]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 45  60  90 140 190 220 240 220 160 110  60  40]]

Форма масиву: (3, 12)

Сума по кожному рядку:
[  87  365 1575]

Середнє по кожному рядку:
[  7.25        30.41666667 131.25      ]

Сума по кожному стовпцю:
[ 70  83 121 179 236 268 291 270 203 148  91  67]


In [7]:
# Завдання 5

rows = np.array([
    temps,
    days_in_month
])

print("Масив rows:")
print(rows)

print("\nФорма rows:", rows.shape)

correction = np.array([1, 0])

print("\nМасив correction:")
print(correction)

print("Форма correction:", correction.shape)

Масив rows:
[[-6 -5  0  9 15 18 20 19 13  7  1 -4]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма rows: (2, 12)

Масив correction:
[1 0]
Форма correction: (2,)


In [8]:
rows + correction

ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [9]:
correction = correction.reshape(2, 1)

print("Нова форма correction:", correction.shape)

result = rows + correction

print("\nРезультат:")
print(result)

Нова форма correction: (2, 1)

Результат:
[[-5 -4  1 10 16 19 21 20 14  8  2 -3]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


# Письмові відповіді

### 1. Чи можете ви пояснити різницю між shape == (12,) і shape == (1, 12)?

`(12,)` — це одновимірний масив, який містить 12 елементів.

`(1, 12)` — це двовимірний масив, який має 1 рядок і 12 стовпців.

Тобто кількість елементів однакова, але структура масивів різна.

### 2. Чи розумієте, чому temps[temps > 15] повертає масив іншої довжини, ніж temps?

Умова `temps > 15` створює булевий масив True/False. Булева індексація вибирає тільки ті елементи, для яких умова має значення True. Тому результат містить лише температури, що перевищують 15°C, і може мати меншу довжину.

### 3. Що станеться, якщо додати масив форми (3,) до масиву форми (3, 12)?

Безпосереднє додавання дасть помилку broadcasting. Форми `(3,)` і `(3, 12)` несумісні, тому що при порівнянні останніх вимірів отримуємо 3 і 12, які не збігаються і жоден із них не дорівнює 1.

Щоб додавання працювало для трьох рядків, масив форми `(3,)` можна перетворити на `(3, 1)`.

### 4. Чому rows + correction спочатку дає помилку, а rows + correction.reshape(2, 1) — ні?

`rows` має форму `(2, 12)`, а `correction` — `(2,)`. Під час broadcasting останній вимір `2` порівнюється з `12`, тому форми несумісні.

Після `correction.reshape(2, 1)` форма стає `(2, 1)`. Розмір 1 може бути розширений до 12, тому масив можна додати до `rows` форми `(2, 12)`.