# Практика 1. Робоче середовище і NumPy

**Варіант 1: Київ**

Мета: закріпити створення масивів NumPy, векторизовані обчислення, булеву індексацію, агрегати з `axis`, `reshape` та broadcasting.

> Якщо у вас інший варіант, замініть `temps` у клітинці нижче на дані свого міста.

## Перевірка середовища

У локальному VS Code потрібні Python, Jupyter і NumPy. Кернел ноутбука має відповідати середовищу, де встановлено NumPy.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.4


## Перша клітинка

Створимо одновимірний масив і перевіримо його форму та тип даних.

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


## Завдання 1. Створення масивів

Дані для Києва: середньомісячні температури у градусах Цельсія. `days_in_month` відповідає невисокосному року.

In [3]:
city = "Київ"
temps = np.array([-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2])
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
month_numbers = np.arange(1, 13)

print("Місто:", city)
print("temps:", temps, "shape:", temps.shape, "dtype:", temps.dtype)
print("days_in_month:", days_in_month, "shape:", days_in_month.shape, "dtype:", days_in_month.dtype)
print("month_numbers:", month_numbers, "shape:", month_numbers.shape, "dtype:", month_numbers.dtype)

Місто: Київ
temps: [-4 -3  2  9 15 19 21 20 14  8  2 -2] shape: (12,) dtype: int64
days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31] shape: (12,) dtype: int64
month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12] shape: (12,) dtype: int64


## Завдання 2. Векторизовані обчислення

Переводимо температури у Фаренгейти без циклу, рахуємо кількість днів із температурою понад 15 °C і перевіряємо довжину року.

In [4]:
temps_f = temps * 9 / 5 + 32
warm_days = days_in_month[temps > 15].sum()
year_days = days_in_month.sum()

print("Температури у °F:", temps_f)
print("Днів тепліше 15 °C:", warm_days)
print("Днів у році:", year_days)
assert year_days == 365

Температури у °F: [24.8 26.6 35.6 48.2 59.  66.2 69.8 68.  57.2 46.4 35.6 28.4]
Днів тепліше 15 °C: 92
Днів у році: 365


## Завдання 3. Індексація і фільтрація

In [5]:
warmest_index = temps.argmax()
coldest_index = temps.argmin()

print("Найтепліший місяць:", month_numbers[warmest_index], ",", temps[warmest_index], "°C")
print("Найхолодніший місяць:", month_numbers[coldest_index], ",", temps[coldest_index], "°C")
print("Місяці з температурою нижче нуля:", month_numbers[temps < 0])
print("Відсортовані температури:", np.sort(temps))
print("Оригінальний temps не змінено:", temps)

Найтепліший місяць: 7 , 21 °C
Найхолодніший місяць: 1 , -4 °C
Місяці з температурою нижче нуля: [ 1  2 12]
Відсортовані температури: [-4 -3 -2  2  2  8  9 14 15 19 20 21]
Оригінальний temps не змінено: [-4 -3  2  9 15 19 21 20 14  8  2 -2]


## Завдання 4. Двовимірний масив і `axis`

Третій рядок є умовною кількістю сонячних годин за місяць для навчальної вправи.

In [6]:
sun_hours = np.array([45, 70, 105, 150, 210, 240, 250, 235, 165, 95, 55, 40])
data = np.array([temps, days_in_month, sun_hours])

print("data:\n", data)
print("Форма data:", data.shape)
print("Сума кожного рядка:", data.sum(axis=1))
print("Середнє кожного рядка:", data.mean(axis=1))
column_sums = data.sum(axis=0)
print("Сума кожного стовпця:", column_sums)

data:
 [[ -4  -3   2   9  15  19  21  20  14   8   2  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 45  70 105 150 210 240 250 235 165  95  55  40]]
Форма data: (3, 12)
Сума кожного рядка: [ 101  365 1660]
Середнє кожного рядка: [  8.41666667  30.41666667 138.33333333]
Сума кожного стовпця: [ 72  95 138 189 256 289 302 286 209 134  87  69]


**Пояснення для січня:** перше число `column_sums` є сумою трьох значень за січень: температури, кількості днів у місяці та умовної кількості сонячних годин. Оскільки це різні одиниці вимірювання, така сума має сенс лише як демонстрація роботи `axis=0`, а не як фізична характеристика.

## Завдання 5. `reshape` і broadcasting

In [7]:
rows = np.array([temps, days_in_month])
correction = np.array([1, 0])

print("Форма rows:", rows.shape)
print("Форма correction:", correction.shape)

try:
    rows + correction
except ValueError as error:
    print("Очікувана помилка broadcasting:", error)

correction_column = correction.reshape(2, 1)
corrected_rows = rows + correction_column
print("Форма correction_column:", correction_column.shape)
print("Результат після reshape:\n", corrected_rows)

Форма rows: (2, 12)
Форма correction: (2,)
Очікувана помилка broadcasting: operands could not be broadcast together with shapes (2,12) (2,) 
Форма correction_column: (2, 1)
Результат після reshape:
 [[-3 -2  3 10 16 20 22 21 15  9  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


**Пояснення:** `rows` має форму `(2, 12)`, а `correction` — `(2,)`. Під час broadcasting одновимірний масив вирівнюється за останнім виміром, тому порівнюються `12` і `2`, які несумісні. Після `reshape(2, 1)` форми `(2, 12)` і `(2, 1)` сумісні: одиниця розтягується до 12 стовпців, і кожна поправка додається до свого рядка.

## Короткі письмові відповіді

1. `shape == (12,)` означає одновимірний масив із 12 елементів. `shape == (1, 12)` означає двовимірний масив з одним рядком і 12 стовпцями. Це різні структури, хоча кількість елементів однакова.

2. `temps[temps > 15]` повертає лише елементи, які задовольняють умову. Тому результат має довжину, що дорівнює кількості місяців із температурою понад 15 °C, а не обов'язково 12.

3. Додавання масиву форми `(3,)` до масиву форми `(3, 12)` дає помилку: останні виміри мають розміри 12 і 3, які не дорівнюють одне одному і жоден із них не дорівнює 1. Для додавання поправок до трьох рядків потрібна форма `(3, 1)`.

4. `rows + correction` дає помилку через несумісність `(2, 12)` і `(2,)` за останнім виміром. Після `correction.reshape(2, 1)` форми стають `(2, 12)` і `(2, 1)`, тому одиничний стовпець розширюється вздовж 12 стовпців.