Письмові відповіді

1. Чи можете ви пояснити різницю між shape == (12,) і shape == (1, 12)?

`shape == (12,)` означає одновимірний масив із 12 елементів. У нього немає окремого виміру для рядка та стовпця.

`shape == (1, 12)` означає двовимірний масив, який має 1 рядок і 12 стовпців.

Тобто `(12,)` і `(1, 12)` — це різні форми масивів, хоча в них однакова кількість елементів.

2. Чи розумієте, чому temps[temps > 15] повертає масив іншої довжини, ніж temps?

`temps > 15` створює булевий масив такої самої довжини, як `temps`. Для кожної температури отримуємо `True` або `False`.

Під час `temps[temps > 15]` NumPy залишає тільки ті елементи, для яких умова має значення `True`. Тому результат містить лише температури понад 15°C і може мати меншу довжину, ніж початковий масив `temps`.

Для мого варіанта це температури 16, 20, 23, 22 і 17°C, тому результат має 5 елементів.

3. Чи можете пояснити, що станеться, якщо додати масив форми (3,) до масиву форми (3, 12)?

Масив форми `(3,)` не зможе напряму додатися до масиву форми `(3, 12)` через broadcasting.

NumPy порівнює форми справа наліво. Отримаємо порівняння `12` і `3`. Вони несумісні, оскільки не однакові і жодне з них не дорівнює 1.

Тому така операція призведе до помилки broadcasting.

Щоб додавання працювало для кожного з трьох рядків, масив поправок можна перетворити на форму `(3, 1)`.

 4. Чи можете пояснити, чому rows + correction спочатку дає помилку, а rows + correction.reshape(2, 1) — ні?

`rows` має форму `(2, 12)`, а `correction` має форму `(2,)`.

Під час broadcasting NumPy порівнює розміри справа наліво: `12` і `2`. Вони несумісні, тому виникає помилка.

Після `correction.reshape(2, 1)` форма поправки стає `(2, 1)`. Тепер форми `(2, 12)` і `(2, 1)` сумісні: перші розміри однакові, а розмір `1` може бути розширений до `12`.

Тому поправка `[1, 0]` застосовується до рядків: до всіх значень першого рядка додається 1, а до другого додається 0.


In [24]:
correction_2d = correction.reshape(2, 1)

print(correction_2d)
print("shape:", correction_2d.shape)
result = rows + correction_2d

print(result)
print("shape:", result.shape)

print("rows:")
print(rows)

print()

print("correction:")
print(correction_2d)

print()

print("rows + correction:")
print(result)



[[1]
 [0]]
shape: (2, 1)
[[ 0  1  5 11 17 21 24 23 18 12  6  2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)
rows:
[[-1  0  4 10 16 20 23 22 17 11  5  1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

correction:
[[1]
 [0]]

rows + correction:
[[ 0  1  5 11 17 21 24 23 18 12  6  2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


In [20]:
rows = np.array([temps, days_in_month])

print(rows)
print("shape:", rows.shape)
correction = np.array([1, 0])

print(correction)
print("shape:", correction.shape)


[[-1  0  4 10 16 20 23 22 17 11  5  1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)
[1 0]
shape: (2,)


In [19]:
correction = np.array([1, 0])

print(correction)
print("shape:", correction.shape)


[1 0]
shape: (2,)


In [18]:
rows = np.array([temps, days_in_month])

print(rows)
print("shape:", rows.shape)


[[-1  0  4 10 16 20 23 22 17 11  5  1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)


In [17]:
column_sums = data.sum(axis=0)

print("Сума кожного стовпця:")
print(column_sums)


Сума кожного стовпця:
[ 90  98 145 190 267 300 334 313 247 192 115  92]


In [16]:
row_means = data.mean(axis=1)

print("Середнє кожного рядка:")
print(row_means)


Середнє кожного рядка:
[ 10.66666667  30.41666667 157.5       ]


In [15]:
row_sums = data.sum(axis=1)

print("Сума кожного рядка:")
print(row_sums)


Сума кожного рядка:
[ 128  365 1890]


In [14]:
data = np.array([temps, days_in_month, sun_hours])

print(data)
print("shape:", data.shape)


[[ -1   0   4  10  16  20  23  22  17  11   5   1]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 60  70 110 150 220 250 280 260 200 150  80  60]]
shape: (3, 12)


In [13]:
sun_hours = np.array([60, 70, 110, 150, 220, 250, 280, 260, 200, 150, 80, 60])

print("Кількість сонячних годин:")
print(sun_hours)


Кількість сонячних годин:
[ 60  70 110 150 220 250 280 260 200 150  80  60]


In [12]:
sorted_temps = np.sort(temps)

print("Відсортовані температури:")
print(sorted_temps)

print()

print("Оригінальний temps:")
print(temps)


Відсортовані температури:
[-1  0  1  4  5 10 11 16 17 20 22 23]

Оригінальний temps:
[-1  0  4 10 16 20 23 22 17 11  5  1]


In [11]:
below_zero = temps < 0

print("Місяці з температурою нижче 0°C:")
print(month_numbers[below_zero])


Місяці з температурою нижче 0°C:
[1]


In [10]:
min_temp = temps.min()
min_index = temps.argmin()

print("Найнижча температура:", min_temp, "°C")
print("Індекс найхолоднішого місяця:", min_index)
print("Номер місяця:", month_numbers[min_index])


Найнижча температура: -1 °C
Індекс найхолоднішого місяця: 0
Номер місяця: 1


In [9]:
max_temp = temps.max()
max_index = temps.argmax()

print("Найвища температура:", max_temp, "°C")
print("Індекс найтеплішого місяця:", max_index)
print("Номер місяця:", month_numbers[max_index])


Найвища температура: 23 °C
Індекс найтеплішого місяця: 6
Номер місяця: 7


In [8]:
total_days = days_in_month.sum()

print("Кількість днів у році:", total_days)
print("Чи дорівнює 365:", total_days == 365)


Кількість днів у році: 365
Чи дорівнює 365: True


In [7]:
warm_months = temps > 15

print(warm_months)

warm_days = days_in_month[temps > 15]

print("Дні у місяцях, де температура > 15°C:")
print(warm_days)

print("Усього днів:", warm_days.sum())



[False False False False  True  True  True  True  True False False False]
Дні у місяцях, де температура > 15°C:
[31 30 31 31 30]
Усього днів: 153


In [5]:
temps_f = temps * 9 / 5 + 32

print("Температура у °C:")
print(temps)

print()

print("Температура у °F:")
print(temps_f)


Температура у °C:
[-1  0  4 10 16 20 23 22 17 11  5  1]

Температура у °F:
[30.2 32.  39.2 50.  60.8 68.  73.4 71.6 62.6 51.8 41.  33.8]


In [4]:
import numpy as np

temps = np.array([-1, 0, 4, 10, 16, 20, 23, 22, 17, 11, 5, 1])

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print()

print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print()

print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)


temps: [-1  0  4 10 16 20 23 22 17 11  5  1]
shape: (12,)
dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


Практика 1. Робоче середовище і NumPy

Варіант №3 — Одеса

Середньомісячні температури за навчальними даними.


In [3]:
Практика 1. Робоче середовище і NumPy

Варіант 3 — Одеса

Середньомісячні температури за навчальними даними.


SyntaxError: invalid character '—' (U+2014) (3264435368.py, line 3)

In [1]:
import numpy as np

print(np.__version__)


2.5.2
