# Практична робота 1. Робоче середовище і NumPy
**Варіант 2 (Львів)**  
**Студент:** Хрустовський Павло  
**Група:** ІТ-42  

**Мета заняття:** налаштувати робоче середовище, створити перший ноутбук і закріпити роботу з масивами NumPy та векторизованими обчисленнями.

## Крок 1. Робоче середовище

In [1]:
import numpy as np
print(np.__version__)

2.5.3


## Крок 2. Перша клітинка

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


## Завдання 1. Створення масивів
* `temps` — масив температур свого варіанта (Варіант 2 — Львів).
* `days_in_month` — кількість днів у кожному місяці (не високосний рік).
* `month_numbers` — номери місяців від 1 до 12, через `np.arange`.

In [3]:
# Варіант 2 (Львів)
temps = np.array([-3, -2, 2, 8, 13, 16, 18, 17, 13, 8, 3, -1])
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape, "dtype:", temps.dtype)
print()
print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape, "dtype:", days_in_month.dtype)
print()
print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape, "dtype:", month_numbers.dtype)

temps: [-3 -2  2  8 13 16 18 17 13  8  3 -1]
shape: (12,) dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,) dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,) dtype: int64


## Завдання 2. Векторизовані обчислення
1. Переведення `temps` із °C у °F без циклу ($°F = °C \times 9/5 + 32$).
2. Кількість днів у році тепліше 15°C через булеву індексацію `temps` і `days_in_month`.
3. Перевірка, що сума `days_in_month` дорівнює 365.

In [4]:
# 1. Переведення у °F
temps_f = temps * 9 / 5 + 32
print("Температури у °F:", temps_f)

# 2. Кількість днів тепліше 15°C
warm_days_count = days_in_month[temps > 15].sum()
print("Днів у році тепліше 15°C:", warm_days_count)

# 3. Перевірка кількості днів
print("Сума днів у році:", days_in_month.sum())
print("Сума дорівнює 365:", days_in_month.sum() == 365)

Температури у °F: [26.6 28.4 35.6 46.4 55.4 60.8 64.4 62.6 55.4 46.4 37.4 30.2]
Днів у році тепліше 15°C: 92
Сума днів у році: 365
Сума дорівнює 365: True


## Завдання 3. Індексація і фільтрація
1. Значення й індекс найтеплішого та найхолоднішого місяця.
2. Номери місяців, де температура нижче нуля (булева індексація по `month_numbers`).
3. Сортування температур за зростанням без зміни оригінального масиву.

In [5]:
# 1. Найтепліший та найхолодніший місяці
print(f"Найтепліший місяць: індекс {temps.argmax()}, значення {temps.max()}°C")
print(f"Найхолодніший місяць: індекс {temps.argmin()}, значення {temps.min()}°C")

# 2. Номери місяців з температурою нижче нуля
print("Номери місяців із температурою < 0°C:", month_numbers[temps < 0])

# 3. Сортування без зміни оригіналу
print("Відсортований масив:", np.sort(temps))
print("Оригінальний temps:", temps)

Найтепліший місяць: індекс 6, значення 18°C
Найхолодніший місяць: індекс 0, значення -3°C
Номери місяців із температурою < 0°C: [ 1  2 12]
Відсортований масив: [-3 -2 -1  2  3  8  8 13 13 16 17 18]
Оригінальний temps: [-3 -2  2  8 13 16 18 17 13  8  3 -1]


## Завдання 4. Двовимірний масив і axis
1. Об'єднання `temps`, `days_in_month` та третього рядка (сонячні години) у масив `data` форми `(3, 12)`.
2. Сума й середнє по кожному рядку (`axis=1`).
3. Сума по кожному стовпцю (`axis=0`) та пояснення числа для січня.

In [6]:
# Третій рядок: кількість сонячних годин за місяць
sunshine_hours = np.array([42, 64, 122, 162, 240, 273, 287, 252, 189, 121, 51, 31])

# Двовимірний масив (3, 12)
data = np.array([temps, days_in_month, sunshine_hours])
print("Масив data (shape):", data.shape)
print(data)

# Сума й середнє по кожному рядку (axis=1)
print("Сума по рядках (axis=1):", data.sum(axis=1))
print("Середнє по рядках (axis=1):", data.mean(axis=1))

# Сума по кожному стовпцю (axis=0)
col_sums = data.sum(axis=0)
print("Сума по стовпцях (axis=0):", col_sums)
print("Сума для першого стовпця (січень):", col_sums[0])

Масив data (shape): (3, 12)
[[ -3  -2   2   8  13  16  18  17  13   8   3  -1]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 42  64 122 162 240 273 287 252 189 121  51  31]]
Сума по рядках (axis=1): [  92  365 1834]
Середнє по рядках (axis=1): [  7.66666667  30.41666667 152.83333333]
Сума по стовпцях (axis=0): [ 70  90 155 200 284 319 336 300 232 160  84  61]
Сума для першого стовпця (січень): 70


**Пояснення значення для першого стовпця (січня):**
Отримане число є сумою першого стовпця матриці: `(-3) + 31 + 42 = 70`.
Це формальна сума трьох різних величин: середньої температури (-3°C), кількості днів (31 день) та сонячних годин (42 год). Оскільки величини мають різні одиниці вимірювання, результат має виключно математичний зміст операції вздовж `axis=0`, але не має прямого фізичного змісту.

## Завдання 5. reshape і broadcasting
1. Масив `rows` форми `(2, 12)`.
2. Масив `correction = np.array([1, 0])`.
3. Спроба виконати `rows + correction` (демонстрація помилки).
4. `correction.reshape(2, 1)` та успішне додавання.

In [7]:
rows = np.array([temps, days_in_month])
print("rows shape:", rows.shape)

correction = np.array([1, 0])
print("correction shape:", correction.shape)

# Спроба додати
try:
    rows + correction
except ValueError as e:
    print("Помилка при rows + correction:", e)

rows shape: (2, 12)
correction shape: (2,)
Помилка при rows + correction: operands could not be broadcast together with shapes (2,12) (2,) 


In [8]:
# Перетворення форми на (2, 1) та додавання
correction_reshaped = correction.reshape(2, 1)
print("correction_reshaped shape:", correction_reshaped.shape)

result = rows + correction_reshaped
print("Результат додавання:\n", result)

correction_reshaped shape: (2, 1)
Результат додавання:
 [[-2 -1  3  9 14 17 19 18 14  9  4  0]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


**Пояснення broadcasting:**
* При `rows + correction` форми `(2, 12)` і `(2,)` порівнюються з кінця: `12` і `2`. Вони не рівні і жоден не дорівнює 1, тому виникає помилка.
* Після `correction.reshape(2, 1)` порівнюються `12` і `1`: вимір `1` автоматично розширюється (broadcast) до `12`. По осі рядків розміри `2` і `2` збігаються. До першого рядка додається 1, до другого — 0.

---
## Відповіді на контрольні запитання

**1. Чи можете ви пояснити різницю між `shape == (12,)` і `shape == (1, 12)`?**  
* `(12,)` — одновимірний масив (вектор, 1 вісь), елементи отримуються через `a[i]`.
* `(1, 12)` — двовимірний масив (матриця з 1 рядка і 12 стовпців, 2 осі), елементи отримуються через `a[0, i]`. Завдяки виміру 1 його можна транслювати по вертикалі.

**2. Чи розумієте, чому `temps[temps > 15]` повертає масив іншої довжини, ніж `temps`?**  
* `temps > 15` створює булеву маску, де `True` тільки для елементів > 15. Булева індексація фільтрує масив і повертає лише елементи, для яких маска має значення `True`. Оскільки не всі місяці тепліші за 15°C, повертається масив меншої довжини.

**3. Чи можете пояснити, що станеться, якщо додати масив форми `(3,)` до масиву форми `(3, 12)`?**  
* Виникне помилка `ValueError`, оскільки при порівнянні форм справа наліво розміри останнього виміру `12` і `3` не збігаються і жоден із них не дорівнює 1. Для коректного додавання масив `(3,)` слід перетворити на `(3, 1)`.

**4. Чи можете пояснити, чому `rows + correction` спочатку дає помилку, а `rows + correction.reshape(2, 1)` — ні?**  
* `rows` має форму `(2, 12)`, а `correction` — `(2,)`. Крайні праві розміри `12` і `2` несумісні.  
* Після `.reshape(2, 1)` праві розміри стають `12` і `1` (розмір 1 розтягується до 12), а ліві — `2` і `2` (збігаються). Масиви стають сумісними за правилами broadcasting.