In [ ]:
# Практична робота №1
## Робоче середовище і NumPy

**Варіант:** 7
**Приймачук Назар ІТ-42

In [2]:
import numpy as np

print(np.__version__)


2.1.3


In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


In [4]:
# Варіант 7 — Івано-Франківськ

import numpy as np

# Середньомісячні температури
temps = np.array([-4, -3, 1, 7, 12, 15, 17, 16, 12, 7, 2, -2])

# Кількість днів у кожному місяці
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

# Номери місяців від 1 до 12
month_numbers = np.arange(1, 13)

# Виведення інформації
print("temps:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print()

print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print()

print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

temps: [-4 -3  1  7 12 15 17 16 12  7  2 -2]
shape: (12,)
dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [5]:
# Варіант 7 — Івано-Франківськ

import numpy as np

# Середньомісячні температури
temps = np.array([-4, -3, 1, 7, 12, 15, 17, 16, 12, 7, 2, -2])

# Кількість днів у кожному місяці
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

# Номери місяців від 1 до 12
month_numbers = np.arange(1, 13)

# Виведення інформації
print("temps:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print()

print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print()

print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

temps: [-4 -3  1  7 12 15 17 16 12  7  2 -2]
shape: (12,)
dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [6]:
# Завдання 2 — Векторизовані обчислення

# 1. Переведення температури з °C у °F
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

# 2. Кількість днів у році, коли температура вища за 15°C
warm_days = days_in_month[temps > 15].sum()

print()
print("Кількість днів тепліше 15°C:", warm_days)

# 3. Перевірка кількості днів у році
total_days = days_in_month.sum()

print("Кількість днів у році:", total_days)
print("Чи дорівнює 365:", total_days == 365)

Температура у °F:
[24.8 26.6 33.8 44.6 53.6 59.  62.6 60.8 53.6 44.6 35.6 28.4]

Кількість днів тепліше 15°C: 62
Кількість днів у році: 365
Чи дорівнює 365: True


In [7]:
# Завдання 3 — Індексація і фільтрація

# 1. Найтепліший і найхолодніший місяць
warmest_index = temps.argmax()
coldest_index = temps.argmin()

print("Найвища температура:", temps[warmest_index], "°C")
print("Індекс найтеплішого місяця:", warmest_index)
print("Номер найтеплішого місяця:", month_numbers[warmest_index])

print()

print("Найнижча температура:", temps[coldest_index], "°C")
print("Індекс найхолоднішого місяця:", coldest_index)
print("Номер найхолоднішого місяця:", month_numbers[coldest_index])

# 2. Місяці з температурою нижче 0°C
below_zero_months = month_numbers[temps < 0]

print()
print("Місяці з температурою нижче 0°C:", below_zero_months)

# 3. Температури за зростанням
sorted_temps = np.sort(temps)

print()
print("Температури за зростанням:", sorted_temps)
print("Оригінальний масив temps:", temps)

Найвища температура: 17 °C
Індекс найтеплішого місяця: 6
Номер найтеплішого місяця: 7

Найнижча температура: -4 °C
Індекс найхолоднішого місяця: 0
Номер найхолоднішого місяця: 1

Місяці з температурою нижче 0°C: [ 1  2 12]

Температури за зростанням: [-4 -3 -2  1  2  7  7 12 12 15 16 17]
Оригінальний масив temps: [-4 -3  1  7 12 15 17 16 12  7  2 -2]


In [8]:
# Завдання 4 — Двовимірний масив і axis

# Умовна кількість сонячних годин за місяць
sun_hours = np.array([55, 70, 110, 150, 190, 210, 230, 215, 160, 110, 65, 45])

# Створюємо двовимірний масив 3 × 12
data = np.array([temps, days_in_month, sun_hours])

print("Двовимірний масив:")
print(data)

print()
print("Форма масиву:", data.shape)

# Сума кожного рядка
print()
print("Сума кожного рядка:")
print(data.sum(axis=1))

# Середнє значення кожного рядка
print()
print("Середнє кожного рядка:")
print(data.mean(axis=1))

# Сума кожного стовпця
print()
print("Сума по кожному стовпцю:")
print(data.sum(axis=0))

# Перший стовпець — січень
print()
print("Січень:", data[:, 0])
print("Сума значень за січень:", data[:, 0].sum())

Двовимірний масив:
[[ -4  -3   1   7  12  15  17  16  12   7   2  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 55  70 110 150 190 210 230 215 160 110  65  45]]

Форма масиву: (3, 12)

Сума кожного рядка:
[  80  365 1610]

Середнє кожного рядка:
[  6.66666667  30.41666667 134.16666667]

Сума по кожному стовпцю:
[ 82  95 142 187 233 255 278 262 202 148  97  74]

Січень: [-4 31 55]
Сума значень за січень: 82


In [10]:
# Завдання 5 — reshape і broadcasting

# Двовимірний масив 2 × 12
rows = np.array([temps, days_in_month])

print("rows:")
print(rows)

print()
print("Форма rows:", rows.shape)

# Поправка для кожного рядка
correction = np.array([1, 0])

print()
print("correction:", correction)
print("Форма correction:", correction.shape)
# Спроба додавання
rows + correction

rows:
[[-4 -3  1  7 12 15 17 16 12  7  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма rows: (2, 12)

correction: [1 0]
Форма correction: (2,)


ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [11]:
# Змінюємо форму correction з (2,) на (2, 1)
correction_reshaped = correction.reshape(2, 1)

print("Нова форма correction:", correction_reshaped.shape)
print(correction_reshaped)

# Тепер додавання працює
result = rows + correction_reshaped

print()
print("Результат:")
print(result)

Нова форма correction: (2, 1)
[[1]
 [0]]

Результат:
[[-3 -2  2  8 13 16 18 17 13  8  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


# Письмові відповіді

 1. Чи можете ви пояснити різницю між shape == (12,) і shape == (1, 12)?

`shape == (12,)` означає, що масив є одновимірним і містить 12 елементів.

`shape == (1, 12)` означає, що масив є двовимірним та має 1 рядок і 12 стовпців.

Отже, ці масиви містять однакову кількість значень, але мають різну структуру та розмірність.

 2. Чи розумієте, чому temps[temps > 15] повертає масив іншої довжини, ніж temps?

Умова `temps > 15` створює булевий масив, де для кожного елемента вказано `True` або `False`.

Під час булевої індексації NumPy залишає тільки ті значення, для яких умова є `True`. Тому результат може мати меншу довжину, ніж початковий масив `temps`.

 3. Що станеться, якщо додати масив форми (3,) до масиву форми (3, 12)?

Масиви форм `(3, 12)` і `(3,)` несумісні для broadcasting.

NumPy порівнює розміри справа наліво: `12` і `3` не збігаються і не є одиницею. Тому виникне помилка `ValueError`.

### 4. Чому rows + correction спочатку дає помилку, а rows + correction.reshape(2, 1) — ні?

`rows` має форму `(2, 12)`, а `correction` має форму `(2,)`.

При додаванні NumPy порівнює розміри справа наліво. Розміри `12` і `2` несумісні, тому виникає помилка.

Після `correction.reshape(2, 1)` масив `correction` має форму `(2, 1)`. Тепер одиниця може бути розширена до 12 за допомогою broadcasting, тому додавання виконується успішно.