In [5]:
import numpy as np

print(np.__version__)

2.5.3


In [12]:
rows = np.array([temps, days_in_month])

print(rows)
print("shape:", rows.shape)

[[-4 -3  2  9 15 19 21 20 14  8  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)


In [13]:
correction = np.array([1, 0])

print(correction)
print("shape:", correction.shape)

[1 0]
shape: (2,)


In [14]:
rows + correction

ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [15]:
correction_reshaped = correction.reshape(2, 1)

print(correction_reshaped)
print("shape:", correction_reshaped.shape)

[[1]
 [0]]
shape: (2, 1)


In [16]:
result = rows + correction_reshaped

print(result)
print("shape:", result.shape)

[[-3 -2  3 10 16 20 22 21 15  9  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)


In [17]:
result = rows + correction_reshaped

print(result)
print("shape:", result.shape)

[[-3 -2  3 10 16 20 22 21 15  9  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)


**1. Чи можете ви пояснити різницю між `shape == (12,)` і `shape == (1, 12)`?**

`shape == (12,)` — це одновимірний масив із 12 елементів.
`shape == (1, 12)` — це двовимірний масив із 1 рядком і 12 стовпцями. Це різні форми масивів, хоча кількість елементів однакова.

**2. Чи розумієте, чому `temps[temps > 15]` повертає масив іншої довжини, ніж `temps`?**

`temps > 15` створює булевий масив, у якому для кожної температури вказано `True` або `False`. При індексації `temps[temps > 15]` вибираються тільки ті температури, для яких умова має значення `True`. Тому результат містить лише температури, що більші за 15°C, і може мати меншу довжину, ніж `temps`.

**3. Чи можете пояснити, що станеться, якщо додати масив форми `(3,)` до масиву форми `(3, 12)`?**

Виникне помилка broadcasting. NumPy порівнює форми справа наліво: `12` і `3` не є сумісними розмірами. Тому масив форми `(3,)` не можна безпосередньо додати до масиву форми `(3, 12)`.

**4. Чи можете пояснити, чому `rows + correction` спочатку дає помилку, а `rows + correction.reshape(2, 1)` — ні?**

`rows` має форму `(2, 12)`, а `correction` — `(2,)`. При додаванні NumPy порівнює розміри справа наліво, тому `12` і `2` несумісні. Після `correction.reshape(2, 1)` форма стає `(2, 1)`. Тепер розміри `12` і `1` сумісні, тому NumPy повторює значення поправок по стовпцях і виконує додавання.


In [11]:
print(temps)
print(days_in_month)

[-4 -3  2  9 15 19 21 20 14  8  2 -2]
[31 28 31 30 31 30 31 31 30 31 30 31]


In [4]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -------- ------------------------------- 2.6/12.6 MB 10.1 MB/s eta 0:00:01
   --------------- ------------------------ 5.0/12.6 MB 11.0 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 11.2 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.7 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


In [5]:
import numpy as np

temps = np.array([-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2])

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

temps: [-4 -3  2  9 15 19 21 20 14  8  2 -2]
shape: (12,)
dtype: int64
days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64
month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [6]:
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

warm_days = days_in_month[temps > 15]

print("Дні у місяцях з температурою вище 15°C:")
print(warm_days)

print("Всього днів тепліше 15°C:", warm_days.sum())

print("Сума днів у році:", days_in_month.sum())
print("Чи дорівнює 365:", days_in_month.sum() == 365)

Температура у °F:
[24.8 26.6 35.6 48.2 59.  66.2 69.8 68.  57.2 46.4 35.6 28.4]
Дні у місяцях з температурою вище 15°C:
[30 31 31]
Всього днів тепліше 15°C: 92
Сума днів у році: 365
Чи дорівнює 365: True


In [8]:
warmest_index = temps.argmax()
coldest_index = temps.argmin()

print("Найтепліший місяць:")
print("Температура:", temps[warmest_index], "°C")
print("Індекс:", warmest_index)
print("Номер місяця:", month_numbers[warmest_index])

print("\nНайхолодніший місяць:")
print("Температура:", temps[coldest_index], "°C")
print("Індекс:", coldest_index)
print("Номер місяця:", month_numbers[coldest_index])

cold_months = month_numbers[temps < 0]

print("\nМісяці з температурою нижче 0°C:")
print(cold_months)

sorted_temps = np.sort(temps)

print("\nТемператури за зростанням:")
print(sorted_temps)

print("\nОригінальний масив temps:")
print(temps)

Найтепліший місяць:
Температура: 21 °C
Індекс: 6
Номер місяця: 7

Найхолодніший місяць:
Температура: -4 °C
Індекс: 0
Номер місяця: 1

Місяці з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-4 -3 -2  2  2  8  9 14 15 19 20 21]

Оригінальний масив temps:
[-4 -3  2  9 15 19 21 20 14  8  2 -2]


In [9]:
sun_hours = np.array([50, 70, 110, 150, 190, 230, 250, 240, 180, 130, 70, 45])

data = np.array([temps, days_in_month, sun_hours])

print("Двовимірний масив:")
print(data)

print("\nФорма масиву:")
print(data.shape)

print("\nСума кожного рядка:")
print(data.sum(axis=1))

print("\nСереднє кожного рядка:")
print(data.mean(axis=1))

print("\nСума кожного стовпця:")
print(data.sum(axis=0))

print("\nСума для січня:", data[:, 0].sum())

Двовимірний масив:
[[ -4  -3   2   9  15  19  21  20  14   8   2  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 50  70 110 150 190 230 250 240 180 130  70  45]]

Форма масиву:
(3, 12)

Сума кожного рядка:
[ 101  365 1715]

Середнє кожного рядка:
[  8.41666667  30.41666667 142.91666667]

Сума кожного стовпця:
[ 77  95 143 189 236 279 302 291 224 169 102  74]

Сума для січня: 77


Для січня отримане число означає суму трьох значень: температури, кількості днів у місяці та умовної кількості сонячних годин: -4 + 31 + 50 = 77. Сума для січня дорівнює 77.